version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
    expose:
      - "3000"

  proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
